services:
  app:
    image: fastapi-todo-api:local
    build:
      context: .
      target: local
    ports:
      - 8080:8080
    environment:
      DB_URI: "postgresql+asyncpg://postgres:password@postgres:5432"
      USE_CONSOLE_LOG: true
      PYTHONWARNINGS: default
      PYTHONASYNCIODEBUG: 1
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/app
      - venv:/app/.venv
    depends_on:
      - postgres
    develop:
      watch:
        - action: rebuild
          path: ./uv.lock
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  venv:
  postgres_data:
